random_seed: 1126
device:
  type: cuda
  ordinal: 0
dataset_dir: './dataset/classification'
data_loader:
  max_sent_len: 64
  max_word_len: 16
  batch_size: 32
  n_workers: 4
net:
  char_conv_kernel_size: 3
  d_model: 128
  dropout: 0.1
use_elmo: false
elmo_embedder:
  # Set the value of ``ELMo.embedder`` init parameters here.
  ctx_emb_dim: 0  # The dimension of the contextualized embedding, required.
optim:
  algo: 'Adam'
  kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-6
train:
  n_epochs: 30
  max_grad_norm: 1
  n_gradient_accumulation_steps: 1  # Must be a divider of data_loader.batch_size.
